### ISSUE TITLE
No html page shown / grey page

### ISSUE THREAD

**Issue by Sineos** [SKB-CGN/ioBroker.energiefluss#17]
**Describe the bug**  
"Energiefluss" page is grey with only `Loading Config and Values ...`

![grafik](https://user-images.githubusercontent.com/4459312/187035664-b2790aff-4032-4393-8316-328fd3bcb718.png)

**To Reproduce**  
1. Install
2. Configure (no car, no battery)
3. Open html page

**Expected behavior**  
See animation

**Screenshots & Logfiles**  
```
2022-08-27 16:57:46.480debugStates changed: {"production":15213,"consumption":19082,"grid_feed":45529681.900000006,"grid_consuming":44144700.7
2022-08-27 16:57:46.477debugStates changed: {"production":15213,"consumption":19082,"grid_feed":45529681.900000006,"grid_consuming":44144700.7
2022-08-27 16:57:42.029debugStates changed: {"production":15213,"consumption":19082,"grid_feed":45529681.900000006,"grid_consuming":44144700.7
2022-08-27 16:57:42.028debugStates changed: {"production":15213,"consumption":19082,"grid_feed":45529681.900000006,"grid_consuming":44144700.7
2022-08-27 16:57:40.466debugElements to be displayed: {"house":true,"production":true,"grid":true,"car":false,"battery":false,"custom0":false,"custom1":false,"custom2":false,"custom3":false
2022-08-27 16:57:40.465debugConfiguration build up successfull!
2022-08-27 16:57:40.463debugInitial Values: {"production":15213,"consumption":19082,"grid_feed":45529681.900000006,"grid_consuming":44144700.6
2022-08-27 16:57:40.462infoAdapter started and listening to 4 States
2022-08-27 16:57:40.457debugRequesting the following states: solarlog.0.INV.WR 1.daysum,solarlog.0.INV.S0-IN B.daysum,0_userdata.0.Consumptions.SML_Energy_Out,0_userdata.0.Consumptions.SML_Energy_In
2022-08-27 16:57:40.448debugAdded States for subscribing: {"production":"solarlog.0.INV.WR 1.daysum","consumption":"solarlog.0.INV.S0-IN B.daysum","grid_feed":"0_userdata.0.Consumptions.SML_Energy_Out","grid_consuming":"0_userdata.0.Consumptions.SML_Energy_In"
2022-08-27 16:57:40.448infoStarting Energiefluss Adapter
2022-08-27 16:57:40.434infostarting. Version 1.1.0 (non-npm: SKB-CGN/ioBroker.energiefluss#2c20e767d1f7a11a5ac553936d56c1bd79ec2e4d) in /opt/iobroker/node_modules/iobroker.energiefluss, node: v16.16.0, js-controller: 4.0.23
2022-08-27 16:57:36.981infoTerminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-08-27 16:57:36.981infoterminating
2022-08-27 16:57:36.980infoGot terminate signal TERMINATE_YOURSELF
```

**Comment by SKB-CGN** [comment]
Please provide Browser Console Output from F12.

**Comment by Sineos** [comment]
[2022-08-27T16:29:36.530Z] ws connection error: CLOSE_ABNORMAL socket.io.js:68:32
[2022-08-27T16:29:36.530Z] Start reconnect 5 socket.io.js:66:41
Using Instance: energiefluss.0 functions.js:9:9
[2022-08-27T16:29:36.622Z] Try to connect socket.io.js:66:41
[2022-08-27T16:29:39.633Z] No READY flag received in 3 seconds. Re-init socket.io.js:67:32
[2022-08-27T16:29:39.633Z] Start reconnect 0 socket.io.js:66:41
Firefox can’t establish a connection to the server at ws://192.168.178.12:8082/?sid=1661617776623. socket.io.js:140:21
[2022-08-27T16:29:39.633Z] Try to connect socket.io.js:66:41
The connection to ws://192.168.178.12:8082/?sid=1661617776623 was interrupted while the page was loading. socket.io.js:140:21
[2022-08-27T16:29:39.635Z] Start reconnect 1 socket.io.js:66:41
[2022-08-27T16:29:39.635Z] ws connection error: CLOSE_ABNORMAL socket.io.js:68:32
[2022-08-27T16:29:39.635Z] Reconnect is already running 1 socket.io.js:66:41
Firefox can’t establish a connection to the server at ws://192.168.178.12:8082/?sid=1661617779633. socket.io.js:140:21
The connection to ws://192.168.178.12:8082/?sid=1661617779633 was interrupted while the page was loading. socket.io.js:140:21
[2022-08-27T16:29:39.635Z] Reconnect is already running 1 socket.io.js:66:41
[2022-08-27T16:29:39.635Z] ws connection error: CLOSE_ABNORMAL socket.io.js:68:32
[2022-08-27T16:29:39.635Z] Reconnect is already running 1 socket.io.js:66:41
[2022-08-27T16:29:40.647Z] Try to connect socket.io.js:66:41
[2022-08-27T16:29:43.651Z] No READY flag received in 3 seconds. Re-init socket.io.js:67:32
[2022-08-27T16:29:43.651Z] Start reconnect 2 socket.io.js:66:41
Firefox can’t establish a connection to the server at ws://192.168.178.12:8082/?sid=1661617780647. socket.io.js:140:21
The connection to ws://192.168.178.12:8082/?sid=1661617780647 was interrupted while the page was loading. socket.io.js:140:21
[2022-08-27T16:29:43.652Z] Reconnect is already running 2 socket.io.js:66:41
[2022-08-27T16:29:43.652Z] ws connection error: CLOSE_ABNORMAL socket.io.js:68:32
[2022-08-27T16:29:43.652Z] Reconnect is already running 2 socket.io.js:66:41
[2022-08-27T16:29:45.657Z] Try to connect socket.io.js:66:41
[2022-08-27T16:29:48.662Z] No READY flag received in 3 seconds. Re-init socket.io.js:67:32
[2022-08-27T16:29:48.662Z] Start reconnect 3 socket.io.js:66:41
Firefox can’t establish a connection to the server at ws://192.168.178.12:8082/?sid=1661617785658. socket.io.js:140:21
The connection to ws://192.168.178.12:8082/?sid=1661617785658 was interrupted while the page was loading. socket.io.js:140:21
[2022-08-27T16:29:48.663Z] Reconnect is already running 3 socket.io.js:66:41
[2022-08-27T16:29:48.663Z] ws connection error: CLOSE_ABNORMAL socket.io.js:68:32
[2022-08-27T16:29:48.663Z] Reconnect is already running 3 socket.io.js:66:41
[2022-08-27T16:29:51.669Z] Try to connect socket.io.js:66:41
[2022-08-27T16:29:54.686Z] No READY flag received in 3 seconds. Re-init socket.io.js:67:32
[2022-08-27T16:29:54.686Z] Start reconnect 4 socket.io.js:66:41
Firefox can’t establish a connection to the server at ws://192.168.178.12:8082/?sid=1661617791669. socket.io.js:140:21
The connection to ws://192.168.178.12:8082/?sid=1661617791669 was interrupted while the page was loading. socket.io.js:140:21
[2022-08-27T16:29:54.687Z] Reconnect is already running 4 socket.io.js:66:41
[2022-08-27T16:29:54.687Z] ws connection error: CLOSE_ABNORMAL socket.io.js:68:32
[2022-08-27T16:29:54.687Z] Reconnect is already running 4 socket.io.js:66:41
[2022-08-27T16:29:58.695Z] Try to connect socket.io.js:66:41
[2022-08-27T16:30:01.707Z] No READY flag received in 3 seconds. Re-init socket.io.js:67:32
[2022-08-27T16:30:01.707Z] Start reconnect 5 socket.io.js:66:41
Firefox can’t establish a connection to the server at ws://192.168.178.12:8082/?sid=1661617798695. socket.io.js:140:21
The connection to ws://192.168.178.12:8082/?sid=1661617798695 was interrupted while the page was loading. socket.io.js:140:21
[2022-08-27T16:30:01.709Z] Reconnect is already running 5 socket.io.js:66:41
[2022-08-27T16:30:01.709Z] ws connection error: CLOSE_ABNORMAL socket.io.js:68:32
[2022-08-27T16:30:01.709Z] Reconnect is already running 5 socket.io.js:66:41
[2022-08-27T16:30:06.717Z] Try to connect socket.io.js:66:41
GETws://192.168.178.12:8082/?sid=1661617806717
[HTTP/1.1 404 Not Found 1ms]
Firefox can’t establish a connection to the server at ws://192.168.178.12:8082/?sid=1661617806717. socket.io.js:140:21
[2022-08-27T16:30:06.725Z] Start reconnect 5 socket.io.js:66:41
[2022-08-27T16:30:06.725Z] ws connection error: CLOSE_ABNORMAL socket.io.js:68:32
[2022-08-27T16:30:06.725Z] Reconnect is already running 5 socket.io.js:66:41

Socket.io is up and running:
![grafik](https://user-images.githubusercontent.com/4459312/187039378-256d4d4b-5eb2-4886-b0ce-0a6284db800c.png)

**Comment by SKB-CGN** [comment]
Please change change in Web Adapter socket instance to integrated. Then the connection is working. 

Do you need socket.io?
In most cases the integrated socket instance in Web Adapter is working fine.

**Comment by Sineos** [comment]
In fact the web adapter is using web sockets:

![grafik](https://user-images.githubusercontent.com/4459312/187041836-91f45066-7720-4bcf-b6d2-fa5d6cfe8368.png)

Otherwise the VIS editor is not working correctly for me

**Comment by SKB-CGN** [comment]
Instance integrated is also working with VIS under all "standard" conditions.

What is not working inside the VIS Editor, if on integrated instance?

Currently, I am not able to provide any other solution.

**Comment by Sineos** [comment]
> What is not working inside the VIS Editor, if on integrated instance?

For example importing projects. Have not encountered anything else but this one for sure is not working under "integrated" and also not working under "socket.io" (at least for me - just retested it)

**Comment by SKB-CGN** [comment]
Means, that one is neither working with integrated and socket?

So, why using socket instead of integrated? :)

**Comment by Sineos** [comment]
Sorry for not being clear. As stated in https://github.com/SKB-CGN/ioBroker.energiefluss/issues/17#issuecomment-1229234717 I'm using the web instance with web-sockets because otherwise the VIS editor is not fully working.

Energiefluss is only working with "integrated" in the web instance but not with "socket.io" and also not with "web-socket".
Testing with socket.io was only during troubleshooting VIS and Energiefluss

**Comment by SKB-CGN** [comment]
Ah ok. Currently the adapter only works with integrated. Sorry for this.
