### ISSUE TITLE
URIError: Failed to decode param

### ISSUE THREAD

**Issue by Toskache** [SKB-CGN/ioBroker.energiefluss#43]
Hallo,

leider kann ich trotz laufender Instanz die "Energiefluss-Website" nicht aufrufen. Es wird immer folgender Fehler angezeigt:

`URIError: Failed to decode param '%web_protocol%://192.168.2.4:%web_port%/energiefluss/index.html'
    at decodeURIComponent (<anonymous>)
    at decode_param (/opt/iobroker/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/opt/iobroker/node_modules/express/lib/router/layer.js:148:15)
    at matchLayer (/opt/iobroker/node_modules/express/lib/router/index.js:585:18)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:226:15)
    at compression (/opt/iobroker/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:328:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:346:12)`

Im Protokoll sieht man auch, dass sich der Adapter regelmäßig selber neu startet.

![image](https://user-images.githubusercontent.com/41288560/192457506-4317970f-4b73-4cec-a50f-603a010aa12d.png)

![image](https://user-images.githubusercontent.com/41288560/192457420-6afde314-37d3-4a19-9b39-c51ee20c5513.png)

![image](https://user-images.githubusercontent.com/41288560/192457563-f1621902-68f1-477b-bcfc-bed0f9905326.png)

![image](https://user-images.githubusercontent.com/41288560/192457933-8126595b-abad-4855-a921-e7ac1b86e84b.png)

Ich vermute er bekommt irgendwie nicht die Serveradresse/Port richtig mit?

**Comment by SKB-CGN** [comment]
Dann würde ich mal schauen, das ich auf eine aktuelle Version des ioBroker komme ;)

**Comment by Toskache** [comment]
> Ist denn der Web-Adapter installiert?

Yeah, das war's!
Bisher hatte ich den wohl nicht gebraucht, da ich nur mit modbus, influxdb, node-red und grafana hantiert habe....

Danke!

**Comment by SKB-CGN** [comment]
Habe hier einmal die "depency" angepasst, das der Web-Adapter mit installiert wird :)
